### ISSUE TITLE
TODO: Mele - Esercizio 8

### ISSUE THREAD

**Issue by KetchDev** [fullstacchioni/git-prova#101]
Esercizio 8

- [x]     Creare un componente mele-Button.tsx
- [x]     Aggiungere il componente mele-Button all'interno del componente pageMele.
- [x]     Eseguire commit.
- [x]     Soluzione quesito
- [x]     Applicazione quesito
- [x]     Eseguire push della branch dedicata.
