### ISSUE TITLE
TODO: Apostolo - Esercizio 8

### ISSUE THREAD

**Issue by Screech46** [fullstacchioni/git-prova#105]
- [x] Creare un componente CognomeButton.tsx all'interno della cartella ./src/components/cognome.
- [x] Aggiungere il componente CognomeButton all'interno del componente pageCognome.
- [x] Eseguire commit.
- [x] Domanda: esiste un modo per "splittare" in 2 commit diverse la modifica di creazione del file CognomeButton.tsx e la modifica di aggiunta del componente CognomeButton al componente pageCognome? Scrivilo in un tag di testo all'interno del file pageCognome.tsx.
- [x] Mettere in pratica la soluzione trovata.
- [x] Eseguire push della branch dedicata.
