### ISSUE TITLE
TODO: Danti - ES 10

### ISSUE THREAD

**Issue by tom-dada** [fullstacchioni/git-prova#108]
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo con scritto: "Angular è il framework più bello del mondo".
- [x] Eseguire commit.
- [x] Eseguire la push.
- [x] Trovare il modo di invertire la commit del punto 2.
