### ISSUE TITLE
TODO: Cacioppo - Esercizio 6

### ISSUE THREAD

**Issue by nadiacacioppo** [fullstacchioni/git-prova#109]

**Comment by nadiacacioppo** [comment]
Esercizio 6:

- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un cantante;
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un attore;
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un calciatore.
