### ISSUE TITLE
TODO: Danti - ES 11

### ISSUE THREAD

**Issue by tom-dada** [fullstacchioni/git-prova#111]
- [x] Esiste un modo per mettere in pausa il lavoro su una branch e riprenderlo in un secondo momento? Scrivilo in un tag di testo all'interno del file page<Cognome>.tsx
- [x] Eseguire commit
- [x] Eseguire push. Eseguire la pull request della branch dedicata verso master.
- [x] Eseguire il merge della pull request.
