### ISSUE TITLE
TODO: Invernizzi - Esercizio 5

### ISSUE THREAD

**Issue by GiacomoInvernizzi** [fullstacchioni/git-prova#114]
- [x] Crea branch invernizzi-multiple-commits
- [x] Aggiungere i vari piatti in pageInvernizzi.tsx
- [x] Aggiungere soluzione in pageInvernizzi.tsx
- [x] Fare lo squash
