### ISSUE TITLE
TODO: Cacioppo - Esercizio 2

### ISSUE THREAD

**Issue by nadiacacioppo** [fullstacchioni/git-prova#12]

**Comment by nadiacacioppo** [comment]
Esercizio 2:

- [ ] Creare un file all'interno della cartella 'pages';
- [ ] All'interno del file creare un componente che mostri il mio nome e cognome;
- [ ] All'interno del file 'users-ts' aggiungere un oggetto con 'name' e 'path';
- [ ] All'interno del file 'router.tsx' aggiungere in children un oggetto con le info di 'path' ed 'element'.
