### ISSUE TITLE
TODO Bellido Es 7 

### ISSUE THREAD

**Issue by Carlobellido** [fullstacchioni/git-prova#125]
Nella branch cognome-perdono:

- [x]  Nel file page.tsx aggiungere un tag di testo con la risposta al seguente quesito: ho eseguito un commit ma mi sono accorto che ho sbagliato a scrivere il messaggio, come posso correggerlo?.

 - [x]  Eseguire commit con messaggio: "cazzotto".
  - [x]  Modificare messaggio in: "scusa"
- [x]  Creare un componente di testo Ammenda.tsx dedicato in cui mettere il tag di testo del punto 1.
- [x]  Aggiungere il nuovo file creato alla commit scusa.
- [x]  Eseguire push della branch dedicata.
 - [x] Creare una pull request della branch dedicata verso master.
 - [x]  Eseguire il merge della pull request.
