### ISSUE TITLE
TODO:Procopio ES_2

### ISSUE THREAD

**Issue by ProGabri** [fullstacchioni/git-prova#13]
- [x] Creare un file page<Cognome>.tsx all'interno della cartella pages (es. pageRossi.tsx).

- [x] All'interno del file creato, creare una componente che mostri, per il momento, il proprio nome e cognome.

- [x] All'interno del file ./src/db/users.ts aggiungere un oggetto con le informazioni sulla propria pagina: name e path.
