### ISSUE TITLE
TODO - BELLIDO - Esercizio 8

### ISSUE THREAD

**Issue by Carlobellido** [fullstacchioni/git-prova#137]
Nella Branch Master : 

- [x] Creare un componente Button.tsx all'interno della cartella ./src/components/.

- [x]  Aggiungere il componente Button all'interno del componente page.
      Eseguire commit.
 
- [x]  Domanda: esiste un modo per "splittare" in 2 commit diverse la modifica di creazione del file Button.tsx e la modifica di aggiunta del componente Button al componente page? Scrivilo in un tag di testo (e.g.
) all'interno del file page.tsx.

- [x]  Mettere in pratica la soluzione trovata.
 
- [x] Eseguire push della branch dedicata.
