### ISSUE TITLE
TODO: Gabancho - es.5

### ISSUE THREAD

**Issue by Gianpaoloits** [fullstacchioni/git-prova#139]

**Comment by Gianpaoloits** [comment]
- [x] Nella branch -multiple-commits:

Nel file page.tsx aggiungere un tag di testo (e.g.
) scrivendo il nome di un antipasto.
-Eseguire commit.

 - [x] Nel file page.tsx aggiungere un tag di testo (e.g.
) scrivendo il nome di un primo.

 Eseguire commit.
 - [ ]Nel file page.tsx aggiungere un tag di testo (e.g.
) scrivendo il nome di un secondo.
-Eseguire commit.

 - [x] Nel file page.tsx aggiungere un tag di testo (e.g.
) scrivendo il nome di un dolce.

 Eseguire commit.
- [x]  Ci ritoviamo con molti commit, come si può fare per unirli in un unico commit? Scrivilo in un tag di testo (e.g.
) all'interno del file page.tsx.
Mettere in pratica la soluzione trovata.

- [ ]Eseguire commit e push della branch dedicata.
- [x]  Creare una pull request della branch dedicata verso master.
 - [x] Eseguire il merge della pull request.
