### ISSUE TITLE
TODO: Palezza es 9

### ISSUE THREAD

**Issue by palezz02** [fullstacchioni/git-prova#142]

**Comment by palezz02** [comment]
- [x] Esiste un modo per riavvolgere il tempo in una branch? Scrivilo in un tag di testo (e.g. <p>) all'interno del file page<Cognome>.tsx.
esegui la commit.

- [x] Modificare a piacere il file page<Cognome>.tsx.
Eseguire commit.

- [x] Riavvolgere il tempo alla commit del punto 2.
Eseguire push.
