### ISSUE TITLE
Todo - Carlo Bellido esercizio 2 

### ISSUE THREAD

**Issue by Carlobellido** [fullstacchioni/git-prova#19]
- [ ] Creare un file page<Cognome>.tsx all'interno della cartella pages (es. pageRossi.tsx).
- [ ] All'interno del file creato, creare una componente che mostri, per il momento, il proprio nome e cognome.
- [ ] All'interno del file ./src/db/users.ts aggiungere un oggetto con le informazioni sulla propria pagina: name e path.
- [ ] All'interno del file ./src/routing/router.tsx aggiungere nell'array children un oggetto con le informazioni sulla propria pagina: path ed element.
- [ ] A questo eseguire commit dedicate per ogni file modificato/creato.
- [ ] Eseguire la push della branch.
- [ ] Creare una pull request della branch verso master.
- [ ] Eseguire il merge della pull request.
- [ ] NON cancellare la branch <cognome>-init.
