### ISSUE TITLE
TODO: Apostolo - Esercizio 3

### ISSUE THREAD

**Issue by Screech46** [fullstacchioni/git-prova#22]
- [x] Nella cartella ./src/components creare una cartella con il proprio cognome.
- [x] Nella propria cartella creare un file Logo.tsx che mostri un'instestazione con il proprio nome e cognome.
- [x] Aggiungere il componente Logo all'interno del componente pageCognome.
- [x] Eseguire commit senza push della branch.
- [x] Trovare il modo di spostare le modifiche fatte su un'altra branch dedicata ripulendo master.
- [x] All'interno del componente pageCognome aggiungere un tag di testo con la soluzione (breve) che hai trovato.
