### ISSUE TITLE
TODO: Invernizzi - Esercizio 2

### ISSUE THREAD

**Issue by GiacomoInvernizzi** [fullstacchioni/git-prova#25]
- [x] Creazione componente pageInvernizzi.tsx all'interno della cartella pages che mostri nome e cognome
- [x] Aggiungere oggetto in ./src/db/users.ts con informazioni relative a name e path
- [x] All'interno del file ./src/routing/router.tsx aggiungere nell'array children un oggetto con le informazioni sulla propria pagina: path ed element
