### ISSUE TITLE
TODO: Parra Rodriguez Es 3

### ISSUE THREAD

**Issue by Manuel9593** [fullstacchioni/git-prova#32]

**Comment by Manuel9593** [comment]
- [x] creare componente logo con intestazione componente
- [x] aggiungere logo a pageCognome
- [x] spostare le modifiche precedenti su un'altra branch
- [x] tag con la soluzione allo spostamento commit su branch nuova
- [x] commit branch creata
