### ISSUE TITLE
TODO: Cacioppo - Esercizio 3

### ISSUE THREAD

**Issue by nadiacacioppo** [fullstacchioni/git-prova#34]

**Comment by nadiacacioppo** [comment]
Esercizio 3:

- [x] creare una cartella con il proprio cognome in components;
- [x] Nella cartella creare un file 'Logo.tsx' con un'intestazione con il proprio nome e cognome;
- [x] Aggiungere il componente 'Logo' all'interno di 'pageCacioppo';
- [x] All'interno di 'pageCacioppo' aggiungere un tag <p> con la soluzione che hai trovato.
