### ISSUE TITLE
TODO: Gabancho- Esercizio 3

### ISSUE THREAD

**Issue by Gianpaoloits** [fullstacchioni/git-prova#44]

**Comment by Gianpaoloits** [comment]
- [x] nella cartella ./src/components creare una cartella con il proprio cognome
- [x] nella propria cartella creare un file Logo.tsx che mostri un'intestazione con il proprio nome e cognome
- [x] Aggiungere il componente Logo all'interno del componente pageCognome.
- [x] Eseguire commit senza push della branch
- [x] Trovare il modo di spostare le modifiche fatte su un'altra branch dedicata ripulendo master
- [ ] All'interno del componente page< Cognome > aggiungere un tag di testo (e.g. < p >) con la soluzione (breve) che hai trovato
- [ ] Eseguire commit della branch dedicata e push
- [ ] Creare una pull request della branch dedicata verso master
- [ ] Eseguire il merge della pull request
