### ISSUE TITLE
TODO: Danti - ES 4

### ISSUE THREAD

**Issue by tom-dada** [fullstacchioni/git-prova#46]
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo con la soluzione al quesito: la mia branch dedicata è indietro di qualche commit rispetto a master, come faccio a portarla avanti? Cioè, come faccio a portare le modifiche fatte su master sulla mia branch dedicata?
- [x] Mettere in pratica la soluzione trovata.
- [x] Eseguire commit e push della branch dedicata.
- [x] Creare una pull request della branch dedicata verso master.
- [x] Eseguire il merge della pull request.
