### ISSUE TITLE
TODO: Parra Rodriguez - Es 4

### ISSUE THREAD

**Issue by Manuel9593** [fullstacchioni/git-prova#50]

**Comment by Manuel9593** [comment]
- [x] su branch cognome-init inserire soluzione a quesito
- [x] commit della soluzione
- [x] pull & merge request
