### ISSUE TITLE
TODO: Danti - ES 5

### ISSUE THREAD

**Issue by tom-dada** [fullstacchioni/git-prova#52]
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo scrivendo il nome di un antipasto.
- [x]  Eseguire commit.
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo scrivendo il nome di un primo.
- [x] Eseguire commit.
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo scrivendo il nome di un secondo.
- [x] Eseguire commit.
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo scrivendo il nome di un dolce.
- [x] Eseguire commit.
- [x] Ci ritoviamo con molti commit, come si può fare per unirli in un unico commit? Scrivilo in un tag di testo all'interno del file page<Cognome>.tsx.
- [x] Mettere in pratica la soluzione trovata.
- [x] Eseguire commit e push della branch dedicata.
- [x] Creare una pull request della branch dedicata verso master.
- [x] Eseguire il merge della pull request.
