### ISSUE TITLE
TODO: Parra Rodriguez - Es 6

### ISSUE THREAD

**Issue by Manuel9593** [fullstacchioni/git-prova#59]

**Comment by Manuel9593** [comment]
- [x] aggiungere un cantante
- [x] aggiungere un attore
- [x] aggiungere un calciatore
- [x] aggiungere soluzione a questito es 6
- [x] push della master
