### ISSUE TITLE
TODO: Invernizzi - Esercizio 3

### ISSUE THREAD

**Issue by GiacomoInvernizzi** [fullstacchioni/git-prova#63]
- [x] Creare Logo.tsx in ./src/components/invernizzi creando le cartelle mancanti
- [x] Aggiungere il componente Logo all'interno del componente pageInvernizzi
- [x] Creare e spostare modifiche da master a invernizzi-esercizio3
- [x] Modificare pageInvernizzi con soluzione su invernizzi-esercizio3
