### ISSUE TITLE
TODO: Parra Rodriguez - Es 7

### ISSUE THREAD

**Issue by Manuel9593** [fullstacchioni/git-prova#67]

**Comment by Manuel9593** [comment]
- [x] aggiungere soluzione a commit sbagliato
- [x] fare soluzione
- [x] creare componente Ammenda
- [x] aggiungere file al commit precedente
- [x] push della branch
- [x] pull & merge request
