### ISSUE TITLE
TODO: Mele - Esercizio 3

### ISSUE THREAD

**Issue by KetchDev** [fullstacchioni/git-prova#73]
Esercizio 3    

- [X]     Creata cartella mele dentro components(creata anche cartella components dato che mancava)
- [X]     Creato componente logo.tsx
- [X]     Aggiunto componente logo.tsx in pageMele.tsx
- [X]     Eseguire commit senza push della branch.
- [X]     Separare commit sulla branch dedicata e cancellare commit da master
- [X]     Aggiungere paragraph con la soluzione
- [X]     Eseguire commit della branch dedicata e push.
- [X]     Creare una pull request della branch dedicata verso master.
- [X]     Eseguire il merge della pull request.
