### ISSUE TITLE
TODO: Mele - Esercizio 4

### ISSUE THREAD

**Issue by KetchDev** [fullstacchioni/git-prova#74]
Esercizio 4

- [X]     Creare paragraph con soluzione al quesito
- [X]     Mettere in pratica la soluzione trovata.
- [X]     Eseguire commit e push della branch dedicata.
- [X]     Creare una pull request della branch dedicata verso master.
- [X]     Eseguire il merge della pull request.
