### ISSUE TITLE
TODO: Mele - Esercizio 5

### ISSUE THREAD

**Issue by KetchDev** [fullstacchioni/git-prova#75]
Esercizio 5
- [X] Creare antipasto e fare commit
- [X] Creare primo e fare commit
- [X] Creare secondo e fare commit
- [X] Creare dolce e fare commit
- [X] Soluzione quesito
- [x] Applicare soluzione
- [x] Commit e push
- [x] Creare Pull request
- [x] Merge su master
