### ISSUE TITLE
TODO - Bellido Es 5

### ISSUE THREAD

**Issue by Carlobellido** [fullstacchioni/git-prova#78]

**Comment by Carlobellido** [comment]
Nella branch <cognome>-multiple-commits:

- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un antipasto. 
 -Eseguire commit.
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un primo.
 - Eseguire commit.
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un secondo.
 -Eseguire commit.
 - [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un dolce.
 - Eseguire commit.
 - 
 - [x]  Ci ritoviamo con molti commit, come si può fare per unirli in un unico commit? Scrivilo in un tag di testo (e.g. <p>) all'interno del file page<Cognome>.tsx.
Mettere in pratica la soluzione trovata.
- [x] Eseguire commit e push della branch dedicata.
 - [x] Creare una pull request della branch dedicata verso master.
 - [x] Eseguire il merge della pull request.
