### ISSUE TITLE
TODO:Widad-Es02

### ISSUE THREAD

**Issue by iiamwendy** [fullstacchioni/git-prova#8]

**Comment by iiamwendy** [comment]
- [x] Crea branch <taouaf>-init
- [x] crea file page<Taouaf>.tsx all'interno della cartella pages(es.pageRossi.ysx)
- [x] dentro al file crea un componente che mostri nome e congnome
- [x] All'interno del file ./src/db/users.ts aggiungere un oggetto con le informazioni sulla propria pagina: name e path.
- [x] All'interno del file ./src/routing/router.tsx aggiungere nell'array children un oggetto con le informazioni sulla propria pagina: path ed element.
- [x] A questo eseguire commit dedicate per ogni file modificato/creato.
- [x] fai la push della branch
- [x] Creare una pull request della branch verso master.
- [x] Eseguire il merge della pull request.
