### ISSUE TITLE
TODO: Palezza es 5

### ISSUE THREAD

**Issue by palezz02** [fullstacchioni/git-prova#80]

**Comment by palezz02** [comment]
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un antipasto.
Eseguire commit.
Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un primo.
Eseguire commit.
Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un secondo.
Eseguire commit.
Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un dolce.
Eseguire commit.

- [x] Ci ritoviamo con molti commit, come si può fare per unirli in un unico commit? Scrivilo in un tag di testo (e.g. <p>) all'interno del file page<Cognome>.tsx.
- [x] Mettere in pratica la soluzione trovata.
