### ISSUE TITLE
TODO: Gabancho - Esercizio 2

### ISSUE THREAD

**Issue by Gianpaoloits** [fullstacchioni/git-prova#82]

**Comment by Gianpaoloits** [comment]
- [x] creare una branch cognome-init
- [x] Creare un file page<Cognome>.tsx all'interno della cartella pages (es. pageRossi.tsx).
- [x] All'interno del file creato, creare una componente che mostri, per il momento, il proprio nome e cognome.
- [x] All'interno del file ./src/db/users.ts aggiungere un oggetto con le informazioni sulla propria pagina: name e path.
- [x] All'interno del file ./src/routing/router.tsx aggiungere nell'array children un oggetto con le informazioni sulla propria pagina: path ed element
- [x] A questo eseguire commit dedicate per ogni file modificato/creato.
- [x] Eseguire la push della branch
- [x] Creare una pull request della branch verso master
- [x] Eseguire il merge della pull request
