### ISSUE TITLE
TODO: Apostolo - Esercizio 6

### ISSUE THREAD

**Issue by Screech46** [fullstacchioni/git-prova#87]
- [x] Nel file pageCognome.tsx aggiungere un tag di testo scrivendo il nome di un cantante.
- [x] Eseguire commit.
- [x] Nel file pageCognome.tsx aggiungere un tag di testo scrivendo il nome di un attore.
- [x] Eseguire commit.
- [x] Nel file pageCognome.tsx aggiungere un tag di testo scrivendo il nome di un calciatore.
- [x] Eseguire commit.
- [x] Esiste un modo per unire tutti questi commit in un unico commit quando si esegue il merge su master? Scrivilo in un tag di testo all'interno del file pageCognome.tsx. Si può fare anche con una pull request?
- [x] Mettere in pratica la soluzione trovata. Se la soluzione scelta è eseguita in locale ricordarsi di eseguire push della branch master.
