### ISSUE TITLE
TODO: Mele - Esercizio 6

### ISSUE THREAD

**Issue by KetchDev** [fullstacchioni/git-prova#88]
Esercizio 6

- [X]  Aggiungere cantante e commit
- [X]  Aggiungere attore e commit
- [X]  Aggiungere calciatore e commit
- [X]  Soluzione quesito
- [X]  Applicazione soluzione
