### ISSUE TITLE
TODO: Danti - ES 8

### ISSUE THREAD

**Issue by tom-dada** [fullstacchioni/git-prova#89]
- [x] Creare un componente <Cognome>Button.tsx all'interno della cartella ./src/components/<cognome>.
- [x] Aggiungere il componente <Cognome>Button all'interno del componente page<Cognome>.
- [x] Eseguire commit.
- [x] Domanda: esiste un modo per "splittare" in 2 commit diverse la modifica di creazione del file <Cognome>Button.tsx e la modifica di aggiunta del componente <Cognome>Button al componente page<Cognome>? Scrivilo in un tag di testo all'interno del file page<Cognome>.tsx.
- [x] Mettere in pratica la soluzione trovata.
- [x] Eseguire push della branch dedicata.
