### ISSUE TITLE
TODO: Mele - Esercizio 7

### ISSUE THREAD

**Issue by KetchDev** [fullstacchioni/git-prova#93]
Esercizio 7

- [x]     Soluzione quesito
- [x]     Eseguire commit con messaggio: "cazzotto".
- [x]     Modificare messaggio in: "scusa"
- [x]     Creare un componente di testo Ammenda.tsx dedicato in cui mettere il tag di testo del punto 1.
- [x]     Aggiungere il nuovo file creato alla commit scusa.
- [x]     Eseguire push della branch dedicata.
- [x]     Creare una pull request della branch dedicata verso master.
- [x]     Eseguire il merge della pull request.
