### ISSUE TITLE
TODO: Palezza es 6

### ISSUE THREAD

**Issue by palezz02** [fullstacchioni/git-prova#94]

**Comment by palezz02** [comment]
- [x] Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un cantante.
Eseguire commit.
Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un attore.
Eseguire commit.
Nel file page<Cognome>.tsx aggiungere un tag di testo (e.g. <p>) scrivendo il nome di un calciatore.
Eseguire commit.

- [x] Esiste un modo per unire tutti questi commit in un unico commit quando si esegue il merge su master? Scrivilo in un tag di testo (e.g. <p>) all'interno del file page<Cognome>.tsx. Si può fare anche con una pull request?
- [x] Mettere in pratica la soluzione trovata. Se la soluzione scelta è eseguita in locale ricordarsi di eseguire push della branch master.
