### ISSUE TITLE
TODO: Gabancho- es.3

### ISSUE THREAD

**Issue by Gianpaoloits** [fullstacchioni/git-prova#95]

**Comment by Gianpaoloits** [comment]
- [x] nella cartella ./src/components creare una cartella con il proprio cognome (es. ./src/components/rossi).

 - [x] nella propria cartella creare un file Logo.tsx che mostri un'instestazione con il proprio nome e cognome.

- [x]  Aggiungere il componente Logo all'interno del componente page.

- [x]  Eseguire commit senza push della branch.

- [x]  Trovare il modo di spostare le modifiche fatte su un'altra branch dedicata ripulendo master.

- [x]  All'interno del componente page aggiungere un tag di testo (e.g.

) con la soluzione (breve) che hai trovato.

- [x]  Eseguire commit della branch dedicata e push.

- [x]  Creare una pull request della branch dedicata verso master.

- [x]  Eseguire il merge della pull request.
