### ISSUE TITLE
TODO -BELLIDO ES 6

### ISSUE THREAD

**Issue by Carlobellido** [fullstacchioni/git-prova#96]
Nella branch <cognome>-massive-merge:
- [x] Nel file page.tsx aggiungere un tag di testo scrivendo il nome di un cantante.

 Eseguire commit.

- [x]  Nel file page.tsx aggiungere un tag di testo scrivendo il nome di un attore.

 Eseguire commit.

- [x]  Nel file page.tsx aggiungere un tag di testo scrivendo il nome di un calciatore.

 Eseguire commit.

- [x]  Esiste un modo per unire tutti questi commit in un unico commit quando si esegue il merge su master? Scrivilo in un tag di testo all'interno del file page.tsx. Si può fare anche con una pull request?

 

- [x] Mettere in pratica la soluzione trovata. Se la soluzione scelta è eseguita in locale ricordarsi di eseguire push della branch master.
